services:
  sm-frontend:
    build:
      context: ./frontend
    container_name: sm-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5050/api
    command: npm run dev -- --host 0.0.0.0
    networks:
      - sm-public-net
    depends_on:
      - sm-backend

  sm-backend:
    build:
      context: ./backend
    container_name: sm-backend
    ports:
      - "5050:5050"
    environment:
      PORT: 5050
      MONGO_URI: mongodb://sm-mongo:27017/sm-mern-db
    depends_on:
      - sm-mongo
    networks:
      - sm-private-net
      - sm-public-net

  sm-mongo:
    image: mongo:7
    container_name: sm-mongo
    ports:
      - "27017:27017"
    volumes:
      - sm-mern-db:/data/db
    networks:
      - sm-private-net

volumes:
  sm-mern-db:

networks:
  sm-public-net:
  sm-private-net:
