name: Frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['frontend/**'] # only when frontend code changes

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    environment: simple-mern-todo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Configure AWS Credentials (AWS Academy)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Run S3 Deploy Script
        run: bash scripts/s3-deploy.sh
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          S3_BUCKET: "s3://${{ vars.S3_BUCKET_NAME }}"
